# Generated by Django 2.2.7 on 2019-11-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tracks')),
                ('stem', models.CharField(choices=[('instrumental', 'Instrumental'), ('voice', 'Voice')], max_length=32)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='songs.Song')),
            ],
        ),
    ]
