# Generated by Django 2.2.7 on 2019-12-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='spleeter'),
        ),
    ]
