# Generated by Django 2.2.7 on 2019-11-10 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=256)),
                ('file', models.FileField(blank=True, null=True, upload_to='songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3'])])),
            ],
        ),
        migrations.CreateModel(
            name='SpleeterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spleeter_tasks', to='songs.Song')),
            ],
        ),
    ]
