# Generated by Django 2.2.7 on 2019-12-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='songs.Song')),
            ],
        ),
        migrations.DeleteModel(
            name='SpleeterTask',
        ),
    ]
