# Generated by Django 2.2.7 on 2019-12-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191201_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtask',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
